### ISSUE TITLE
Why the offensive domain?

### ISSUE THREAD

**Issue by jeff-h** [chasseurmic/swiftblocksyntax#3]
Just wondering why you chose the offensive domain name. The site content is great — really helpful!

**Comment by chasseurmic** [comment]
It was just to mimic a pretty famous site about block syntax in Obj-C: http://fuckingblocksyntax.com 

Nothing more nothing less... It wasn't my intention to offend anyone.

**Comment by jeff-h** [comment]
Ah cool — I'm not coming to Swift with much knowledge of Obj-C, hence my ignorance of the other site.

To clarify what I was trying to say, I think the domain name may inadvertently limit the audience the site deserves. It's a really helpful description of Swift closures. Thanks for putting it together.
